#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPacientes
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ControlMedicoPacientes")]
	public partial class BDControlPacienteDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public BDControlPacienteDataContext() : 
				base(global::ControlPacientes.Properties.Settings.Default.ControlMedicoPacientesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BDControlPacienteDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDControlPacienteDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDControlPacienteDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDControlPacienteDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ActualizarConsultorio")]
		public int cp_ActualizarConsultorio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idC, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idMedico)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idC, nombre, idMedico);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ActualizarEnfermera")]
		public int cp_ActualizarEnfermera([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idE, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string titulo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string especialidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string cedula)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idE, titulo, especialidad, cedula);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ActualizarEstadistica")]
		public int cp_ActualizarEstadistica([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCodex, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumCarpeta", DbType="Int")] System.Nullable<int> numCarpeta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idFichaMedica, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCodex, numCarpeta, idFichaMedica, idE);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ActualizarHistorialPaciente")]
		public int cp_ActualizarHistorialPaciente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroConsultas", DbType="Int")] System.Nullable<int> numeroConsultas, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPaciente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idMedico)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idH, numeroConsultas, fecha, idPaciente, idMedico);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ActualizarMedicamento")]
		public int cp_ActualizarMedicamento([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(20)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Peso", DbType="VarChar(20)")] string peso, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo", DbType="VarChar(20)")] string tipo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idM, nombre, peso, tipo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ActualizarPaciente")]
		public int cp_ActualizarPaciente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(15)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Afiliado", DbType="VarChar(10)")] string afiliado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string ced)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idP, estado, afiliado, ced);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_EliminarConsultorio")]
		public int cp_EliminarConsultorio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idC)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idC);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_EliminarEnfermera")]
		public int cp_EliminarEnfermera([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idE);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_EliminarEstadistica")]
		public int cp_EliminarEstadistica([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCodex)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCodex);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_EliminarFichaMedica")]
		public int cp_EliminarFichaMedica([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idFichaM)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idFichaM);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_EliminarHistorialPaciente")]
		public int cp_EliminarHistorialPaciente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idH)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idH);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_EliminarMedicamento")]
		public int cp_EliminarMedicamento([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idM)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idM);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_EliminarMedico")]
		public int cp_EliminarMedico([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idM)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idM);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_EliminarPaciente")]
		public int cp_EliminarPaciente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idP);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_EliminarPersona")]
		public int cp_EliminarPersona([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string ced)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ced);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_InsertarConsultorio")]
		public int cp_InsertarConsultorio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idC, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idMedico)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idC, nombre, idMedico);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_InsertarEnfermera")]
		public int cp_InsertarEnfermera([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idE, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string titulo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string especialidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string cedula)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idE, titulo, especialidad, cedula);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_InsertarEstadistica")]
		public int cp_InsertarEstadistica([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCodex, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumCarpeta", DbType="Int")] System.Nullable<int> numCarpeta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idFichaMedica, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCodex, numCarpeta, idFichaMedica, idE);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_InsertarHistorialPaciente")]
		public int cp_InsertarHistorialPaciente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroConsultas", DbType="Int")] System.Nullable<int> numeroConsultas, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPaciente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idMedico)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idH, numeroConsultas, fecha, idPaciente, idMedico);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_InsertarMedicamento")]
		public int cp_InsertarMedicamento([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(20)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Peso", DbType="VarChar(20)")] string peso, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo", DbType="VarChar(20)")] string tipo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idM, nombre, peso, tipo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_InsertarPaciente")]
		public int cp_InsertarPaciente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(15)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Afiliado", DbType="VarChar(10)")] string afiliado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string ced)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idP, estado, afiliado, ced);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_InsertarPersona")]
		public int cp_InsertarPersona([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string ced, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(15)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="VarChar(15)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string dir, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ciudad", DbType="VarChar(15)")] string ciudad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Celular", DbType="VarChar(10)")] string celular)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ced, nombre, apellido, dir, ciudad, fecha, celular);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarConsultorio")]
		public ISingleResult<cp_ListarConsultorioResult> cp_ListarConsultorio()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<cp_ListarConsultorioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarConsultorioFiltro")]
		public ISingleResult<cp_ListarConsultorioFiltroResult> cp_ListarConsultorioFiltro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(50)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<cp_ListarConsultorioFiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarEnfermera")]
		public ISingleResult<cp_ListarEnfermeraResult> cp_ListarEnfermera()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<cp_ListarEnfermeraResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarEnfermeraFiltro")]
		public ISingleResult<cp_ListarEnfermeraFiltroResult> cp_ListarEnfermeraFiltro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(50)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<cp_ListarEnfermeraFiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarEstadistica")]
		public ISingleResult<cp_ListarEstadisticaResult> cp_ListarEstadistica()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<cp_ListarEstadisticaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarEstadisticaFiltro")]
		public ISingleResult<cp_ListarEstadisticaFiltroResult> cp_ListarEstadisticaFiltro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="Int")] System.Nullable<int> valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<cp_ListarEstadisticaFiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarFichaMedica")]
		public ISingleResult<cp_ListarFichaMedicaResult> cp_ListarFichaMedica()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<cp_ListarFichaMedicaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarHistorialPaciente")]
		public ISingleResult<cp_ListarHistorialPacienteResult> cp_ListarHistorialPaciente()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<cp_ListarHistorialPacienteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarMedicamentoFiltro")]
		public ISingleResult<cp_ListarMedicamentoFiltroResult> cp_ListarMedicamentoFiltro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(20)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<cp_ListarMedicamentoFiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarMedicamentos")]
		public ISingleResult<cp_ListarMedicamentosResult> cp_ListarMedicamentos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<cp_ListarMedicamentosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarPaciente")]
		public ISingleResult<cp_ListarPacienteResult> cp_ListarPaciente()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<cp_ListarPacienteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarPacienteFiltro")]
		public ISingleResult<cp_ListarPacienteFiltroResult> cp_ListarPacienteFiltro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(20)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<cp_ListarPacienteFiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarPersona")]
		public ISingleResult<cp_ListarPersonaResult> cp_ListarPersona()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<cp_ListarPersonaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ActualizarFichaMedica")]
		public int cp_ActualizarFichaMedica([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idFichaM, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPaciente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Madre", DbType="VarChar(50)")] string madre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Padre", DbType="VarChar(50)")] string padre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estudios", DbType="VarChar(50)")] string estudios, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GruposS", DbType="VarChar(20)")] string gruposS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Edad", DbType="Int")] System.Nullable<int> edad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Peso", DbType="VarChar(20)")] string peso, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatura", DbType="VarChar(20)")] string estatura)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idFichaM, idPaciente, madre, padre, estudios, gruposS, edad, peso, estatura);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_InsertarFichaMedica")]
		public int cp_InsertarFichaMedica([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idFichaM, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPaciente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Madre", DbType="VarChar(50)")] string madre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Padre", DbType="VarChar(50)")] string padre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estudios", DbType="VarChar(50)")] string estudios, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GruposS", DbType="VarChar(20)")] string gruposS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Edad", DbType="Int")] System.Nullable<int> edad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Peso", DbType="VarChar(20)")] string peso, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatura", DbType="VarChar(20)")] string estatura)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idFichaM, idPaciente, madre, padre, estudios, gruposS, edad, peso, estatura);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ActualizarPersona")]
		public int cp_ActualizarPersona([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string ced, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(15)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="VarChar(15)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string dir, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ciudad", DbType="VarChar(15)")] string ciudad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Celular", DbType="VarChar(10)")] string celular)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ced, nombre, apellido, dir, ciudad, fecha, celular);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ActualizarRecetas")]
		public int cp_ActualizarRecetas([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> num, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string dosis, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha", DbType="DateTime")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idMedi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idMedico, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPaciente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), num, dosis, fecha, idMedi, idMedico, idPaciente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_EliminarRecetas")]
		public int cp_EliminarRecetas([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> num)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), num);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarRecetas")]
		public ISingleResult<cp_ListarRecetasResult> cp_ListarRecetas()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<cp_ListarRecetasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarRecetasFiltro")]
		public ISingleResult<cp_ListarRecetasFiltroResult> cp_ListarRecetasFiltro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(50)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<cp_ListarRecetasFiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ActualizarRegistarse")]
		public int cp_ActualizarRegistarse([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string ced, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string contra, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string tipo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ced, nom, contra, tipo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarRegistro")]
		public ISingleResult<cp_ListarRegistroResult> cp_ListarRegistro()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<cp_ListarRegistroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_EliminarRegistarse")]
		public int cp_EliminarRegistarse([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string ced)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ced);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_InsertarRecetas")]
		public int cp_InsertarRecetas([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> num, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string dosis, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha", DbType="DateTime")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idMedi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idMedico, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPaciente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), num, dosis, fecha, idMedi, idMedico, idPaciente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_InsertarRegistarse")]
		public int cp_InsertarRegistarse([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string ced, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string contra, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string tipo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ced, nom, contra, tipo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ActualizarLogin")]
		public int cp_ActualizarLogin([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string contra, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string ced)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nom, contra, ced);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_EliminarLogin")]
		public int cp_EliminarLogin([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string ced)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ced);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_InsertarLogin")]
		public int cp_InsertarLogin([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string contra, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string ced)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nom, contra, ced);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarLogin")]
		public ISingleResult<cp_ListarLoginResult> cp_ListarLogin()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<cp_ListarLoginResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ActualizarMedico")]
		public int cp_ActualizarMedico([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Titulo", DbType="VarChar(50)")] string titulo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Especialidad", DbType="VarChar(50)")] string especialidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(50)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string ced)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idM, titulo, especialidad, estado, ced);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_InsertarMedico")]
		public int cp_InsertarMedico([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Titulo", DbType="VarChar(50)")] string titulo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Especialidad", DbType="VarChar(50)")] string especialidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(50)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string ced)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idM, titulo, especialidad, estado, ced);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarMedicoFiltro")]
		public ISingleResult<cp_ListarMedicoFiltroResult> cp_ListarMedicoFiltro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(50)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<cp_ListarMedicoFiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarMedico")]
		public ISingleResult<cp_ListarMedicoResult> cp_ListarMedico()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<cp_ListarMedicoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarRegistroFiltro")]
		public ISingleResult<cp_ListarRegistroFiltroResult> cp_ListarRegistroFiltro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(50)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<cp_ListarRegistroFiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarHistorialPacienteFiltro")]
		public ISingleResult<cp_ListarHistorialPacienteFiltroResult> cp_ListarHistorialPacienteFiltro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(50)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<cp_ListarHistorialPacienteFiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cp_ListarFichaMedicaFiltro")]
		public ISingleResult<cp_ListarFichaMedicaFiltroResult> cp_ListarFichaMedicaFiltro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(50)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<cp_ListarFichaMedicaFiltroResult>)(result.ReturnValue));
		}
	}
	
	public partial class cp_ListarConsultorioResult
	{
		
		private int _idConsultorio;
		
		private string _Nombre;
		
		private int _idMedico;
		
		public cp_ListarConsultorioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idConsultorio", DbType="Int NOT NULL")]
		public int idConsultorio
		{
			get
			{
				return this._idConsultorio;
			}
			set
			{
				if ((this._idConsultorio != value))
				{
					this._idConsultorio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMedico", DbType="Int NOT NULL")]
		public int idMedico
		{
			get
			{
				return this._idMedico;
			}
			set
			{
				if ((this._idMedico != value))
				{
					this._idMedico = value;
				}
			}
		}
	}
	
	public partial class cp_ListarConsultorioFiltroResult
	{
		
		private int _idConsultorio;
		
		private string _Nombre;
		
		private int _idMedico;
		
		public cp_ListarConsultorioFiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idConsultorio", DbType="Int NOT NULL")]
		public int idConsultorio
		{
			get
			{
				return this._idConsultorio;
			}
			set
			{
				if ((this._idConsultorio != value))
				{
					this._idConsultorio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMedico", DbType="Int NOT NULL")]
		public int idMedico
		{
			get
			{
				return this._idMedico;
			}
			set
			{
				if ((this._idMedico != value))
				{
					this._idMedico = value;
				}
			}
		}
	}
	
	public partial class cp_ListarEnfermeraResult
	{
		
		private int _idEnfermera;
		
		private string _Titulo;
		
		private string _Especialidad;
		
		private string _Cedula;
		
		public cp_ListarEnfermeraResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEnfermera", DbType="Int NOT NULL")]
		public int idEnfermera
		{
			get
			{
				return this._idEnfermera;
			}
			set
			{
				if ((this._idEnfermera != value))
				{
					this._idEnfermera = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="VarChar(50)")]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this._Titulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Especialidad", DbType="VarChar(50)")]
		public string Especialidad
		{
			get
			{
				return this._Especialidad;
			}
			set
			{
				if ((this._Especialidad != value))
				{
					this._Especialidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
	}
	
	public partial class cp_ListarEnfermeraFiltroResult
	{
		
		private int _idEnfermera;
		
		private string _Titulo;
		
		private string _Especialidad;
		
		private string _Cedula;
		
		public cp_ListarEnfermeraFiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEnfermera", DbType="Int NOT NULL")]
		public int idEnfermera
		{
			get
			{
				return this._idEnfermera;
			}
			set
			{
				if ((this._idEnfermera != value))
				{
					this._idEnfermera = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="VarChar(50)")]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this._Titulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Especialidad", DbType="VarChar(50)")]
		public string Especialidad
		{
			get
			{
				return this._Especialidad;
			}
			set
			{
				if ((this._Especialidad != value))
				{
					this._Especialidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
	}
	
	public partial class cp_ListarEstadisticaResult
	{
		
		private int _Codigo;
		
		private int _idEnfermera;
		
		private int _NumeroCarpeta;
		
		private int _idFichaMedica;
		
		public cp_ListarEstadisticaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="Int NOT NULL")]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEnfermera", DbType="Int NOT NULL")]
		public int idEnfermera
		{
			get
			{
				return this._idEnfermera;
			}
			set
			{
				if ((this._idEnfermera != value))
				{
					this._idEnfermera = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroCarpeta", DbType="Int NOT NULL")]
		public int NumeroCarpeta
		{
			get
			{
				return this._NumeroCarpeta;
			}
			set
			{
				if ((this._NumeroCarpeta != value))
				{
					this._NumeroCarpeta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idFichaMedica", DbType="Int NOT NULL")]
		public int idFichaMedica
		{
			get
			{
				return this._idFichaMedica;
			}
			set
			{
				if ((this._idFichaMedica != value))
				{
					this._idFichaMedica = value;
				}
			}
		}
	}
	
	public partial class cp_ListarEstadisticaFiltroResult
	{
		
		private int _Codigo;
		
		private int _idEnfermera;
		
		private int _NumeroCarpeta;
		
		private int _idFichaMedica;
		
		public cp_ListarEstadisticaFiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="Int NOT NULL")]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEnfermera", DbType="Int NOT NULL")]
		public int idEnfermera
		{
			get
			{
				return this._idEnfermera;
			}
			set
			{
				if ((this._idEnfermera != value))
				{
					this._idEnfermera = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroCarpeta", DbType="Int NOT NULL")]
		public int NumeroCarpeta
		{
			get
			{
				return this._NumeroCarpeta;
			}
			set
			{
				if ((this._NumeroCarpeta != value))
				{
					this._NumeroCarpeta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idFichaMedica", DbType="Int NOT NULL")]
		public int idFichaMedica
		{
			get
			{
				return this._idFichaMedica;
			}
			set
			{
				if ((this._idFichaMedica != value))
				{
					this._idFichaMedica = value;
				}
			}
		}
	}
	
	public partial class cp_ListarFichaMedicaResult
	{
		
		private int _idFichaMedica;
		
		private System.Nullable<int> _idPaciente;
		
		private string _Madre;
		
		private string _Padre;
		
		private string _Estudios;
		
		private string _GrupoSanguineo;
		
		private System.Nullable<int> _Edad;
		
		private string _Peso;
		
		private string _Talla;
		
		private string _Estatura;
		
		public cp_ListarFichaMedicaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idFichaMedica", DbType="Int NOT NULL")]
		public int idFichaMedica
		{
			get
			{
				return this._idFichaMedica;
			}
			set
			{
				if ((this._idFichaMedica != value))
				{
					this._idFichaMedica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPaciente", DbType="Int")]
		public System.Nullable<int> idPaciente
		{
			get
			{
				return this._idPaciente;
			}
			set
			{
				if ((this._idPaciente != value))
				{
					this._idPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Madre", DbType="VarChar(50)")]
		public string Madre
		{
			get
			{
				return this._Madre;
			}
			set
			{
				if ((this._Madre != value))
				{
					this._Madre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Padre", DbType="VarChar(50)")]
		public string Padre
		{
			get
			{
				return this._Padre;
			}
			set
			{
				if ((this._Padre != value))
				{
					this._Padre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estudios", DbType="VarChar(50)")]
		public string Estudios
		{
			get
			{
				return this._Estudios;
			}
			set
			{
				if ((this._Estudios != value))
				{
					this._Estudios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupoSanguineo", DbType="VarChar(20)")]
		public string GrupoSanguineo
		{
			get
			{
				return this._GrupoSanguineo;
			}
			set
			{
				if ((this._GrupoSanguineo != value))
				{
					this._GrupoSanguineo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edad", DbType="Int")]
		public System.Nullable<int> Edad
		{
			get
			{
				return this._Edad;
			}
			set
			{
				if ((this._Edad != value))
				{
					this._Edad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Peso", DbType="VarChar(20)")]
		public string Peso
		{
			get
			{
				return this._Peso;
			}
			set
			{
				if ((this._Peso != value))
				{
					this._Peso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Talla", DbType="VarChar(20)")]
		public string Talla
		{
			get
			{
				return this._Talla;
			}
			set
			{
				if ((this._Talla != value))
				{
					this._Talla = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatura", DbType="VarChar(20)")]
		public string Estatura
		{
			get
			{
				return this._Estatura;
			}
			set
			{
				if ((this._Estatura != value))
				{
					this._Estatura = value;
				}
			}
		}
	}
	
	public partial class cp_ListarHistorialPacienteResult
	{
		
		private int _idRegistroPaciente;
		
		private System.Nullable<int> _NumeroConsultas;
		
		private System.Nullable<System.DateTime> _UltimaFechaConsulta;
		
		private int _idPaciente;
		
		private int _idMedico;
		
		public cp_ListarHistorialPacienteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRegistroPaciente", DbType="Int NOT NULL")]
		public int idRegistroPaciente
		{
			get
			{
				return this._idRegistroPaciente;
			}
			set
			{
				if ((this._idRegistroPaciente != value))
				{
					this._idRegistroPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroConsultas", DbType="Int")]
		public System.Nullable<int> NumeroConsultas
		{
			get
			{
				return this._NumeroConsultas;
			}
			set
			{
				if ((this._NumeroConsultas != value))
				{
					this._NumeroConsultas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UltimaFechaConsulta", DbType="DateTime")]
		public System.Nullable<System.DateTime> UltimaFechaConsulta
		{
			get
			{
				return this._UltimaFechaConsulta;
			}
			set
			{
				if ((this._UltimaFechaConsulta != value))
				{
					this._UltimaFechaConsulta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPaciente", DbType="Int NOT NULL")]
		public int idPaciente
		{
			get
			{
				return this._idPaciente;
			}
			set
			{
				if ((this._idPaciente != value))
				{
					this._idPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMedico", DbType="Int NOT NULL")]
		public int idMedico
		{
			get
			{
				return this._idMedico;
			}
			set
			{
				if ((this._idMedico != value))
				{
					this._idMedico = value;
				}
			}
		}
	}
	
	public partial class cp_ListarMedicamentoFiltroResult
	{
		
		private int _idMedicamento;
		
		private string _Nombre;
		
		private string _Peso;
		
		private string _Tipo;
		
		public cp_ListarMedicamentoFiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMedicamento", DbType="Int NOT NULL")]
		public int idMedicamento
		{
			get
			{
				return this._idMedicamento;
			}
			set
			{
				if ((this._idMedicamento != value))
				{
					this._idMedicamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(20)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Peso", DbType="VarChar(20)")]
		public string Peso
		{
			get
			{
				return this._Peso;
			}
			set
			{
				if ((this._Peso != value))
				{
					this._Peso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(20)")]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this._Tipo = value;
				}
			}
		}
	}
	
	public partial class cp_ListarMedicamentosResult
	{
		
		private int _idMedicamento;
		
		private string _Nombre;
		
		private string _Peso;
		
		private string _Tipo;
		
		public cp_ListarMedicamentosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMedicamento", DbType="Int NOT NULL")]
		public int idMedicamento
		{
			get
			{
				return this._idMedicamento;
			}
			set
			{
				if ((this._idMedicamento != value))
				{
					this._idMedicamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(20)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Peso", DbType="VarChar(20)")]
		public string Peso
		{
			get
			{
				return this._Peso;
			}
			set
			{
				if ((this._Peso != value))
				{
					this._Peso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(20)")]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this._Tipo = value;
				}
			}
		}
	}
	
	public partial class cp_ListarPacienteResult
	{
		
		private int _idPaciente;
		
		private string _Estado;
		
		private string _AfiliadoSS;
		
		private string _Cedula;
		
		public cp_ListarPacienteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPaciente", DbType="Int NOT NULL")]
		public int idPaciente
		{
			get
			{
				return this._idPaciente;
			}
			set
			{
				if ((this._idPaciente != value))
				{
					this._idPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(15)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AfiliadoSS", DbType="VarChar(10)")]
		public string AfiliadoSS
		{
			get
			{
				return this._AfiliadoSS;
			}
			set
			{
				if ((this._AfiliadoSS != value))
				{
					this._AfiliadoSS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
	}
	
	public partial class cp_ListarPacienteFiltroResult
	{
		
		private int _idPaciente;
		
		private string _Estado;
		
		private string _AfiliadoSS;
		
		private string _Cedula;
		
		public cp_ListarPacienteFiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPaciente", DbType="Int NOT NULL")]
		public int idPaciente
		{
			get
			{
				return this._idPaciente;
			}
			set
			{
				if ((this._idPaciente != value))
				{
					this._idPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(15)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AfiliadoSS", DbType="VarChar(10)")]
		public string AfiliadoSS
		{
			get
			{
				return this._AfiliadoSS;
			}
			set
			{
				if ((this._AfiliadoSS != value))
				{
					this._AfiliadoSS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
	}
	
	public partial class cp_ListarPersonaResult
	{
		
		private string _Cedula;
		
		private string _Nombres;
		
		private string _Apellidos;
		
		private string _Direccion;
		
		private string _Ciudad;
		
		private System.Nullable<System.DateTime> _FechaNacimiento;
		
		private string _Celular;
		
		public cp_ListarPersonaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(15)")]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this._Nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(15)")]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this._Apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ciudad", DbType="VarChar(15)")]
		public string Ciudad
		{
			get
			{
				return this._Ciudad;
			}
			set
			{
				if ((this._Ciudad != value))
				{
					this._Ciudad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this._FechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this._Celular = value;
				}
			}
		}
	}
	
	public partial class cp_ListarRecetasResult
	{
		
		private int _NumeroReceta;
		
		private string _Dosis;
		
		private System.Nullable<System.DateTime> _FechaActual;
		
		private int _idMedicamento;
		
		private int _idMedico;
		
		private int _idPaciente;
		
		public cp_ListarRecetasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroReceta", DbType="Int NOT NULL")]
		public int NumeroReceta
		{
			get
			{
				return this._NumeroReceta;
			}
			set
			{
				if ((this._NumeroReceta != value))
				{
					this._NumeroReceta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dosis", DbType="VarChar(200)")]
		public string Dosis
		{
			get
			{
				return this._Dosis;
			}
			set
			{
				if ((this._Dosis != value))
				{
					this._Dosis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaActual", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaActual
		{
			get
			{
				return this._FechaActual;
			}
			set
			{
				if ((this._FechaActual != value))
				{
					this._FechaActual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMedicamento", DbType="Int NOT NULL")]
		public int idMedicamento
		{
			get
			{
				return this._idMedicamento;
			}
			set
			{
				if ((this._idMedicamento != value))
				{
					this._idMedicamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMedico", DbType="Int NOT NULL")]
		public int idMedico
		{
			get
			{
				return this._idMedico;
			}
			set
			{
				if ((this._idMedico != value))
				{
					this._idMedico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPaciente", DbType="Int NOT NULL")]
		public int idPaciente
		{
			get
			{
				return this._idPaciente;
			}
			set
			{
				if ((this._idPaciente != value))
				{
					this._idPaciente = value;
				}
			}
		}
	}
	
	public partial class cp_ListarRecetasFiltroResult
	{
		
		private int _NumeroReceta;
		
		private string _Dosis;
		
		private System.Nullable<System.DateTime> _FechaActual;
		
		private int _idMedicamento;
		
		private int _idMedico;
		
		private int _idPaciente;
		
		public cp_ListarRecetasFiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroReceta", DbType="Int NOT NULL")]
		public int NumeroReceta
		{
			get
			{
				return this._NumeroReceta;
			}
			set
			{
				if ((this._NumeroReceta != value))
				{
					this._NumeroReceta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dosis", DbType="VarChar(200)")]
		public string Dosis
		{
			get
			{
				return this._Dosis;
			}
			set
			{
				if ((this._Dosis != value))
				{
					this._Dosis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaActual", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaActual
		{
			get
			{
				return this._FechaActual;
			}
			set
			{
				if ((this._FechaActual != value))
				{
					this._FechaActual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMedicamento", DbType="Int NOT NULL")]
		public int idMedicamento
		{
			get
			{
				return this._idMedicamento;
			}
			set
			{
				if ((this._idMedicamento != value))
				{
					this._idMedicamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMedico", DbType="Int NOT NULL")]
		public int idMedico
		{
			get
			{
				return this._idMedico;
			}
			set
			{
				if ((this._idMedico != value))
				{
					this._idMedico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPaciente", DbType="Int NOT NULL")]
		public int idPaciente
		{
			get
			{
				return this._idPaciente;
			}
			set
			{
				if ((this._idPaciente != value))
				{
					this._idPaciente = value;
				}
			}
		}
	}
	
	public partial class cp_ListarRegistroResult
	{
		
		private string _Cedula;
		
		private string _Nombre;
		
		private string _Contraseña;
		
		private string _Tipo;
		
		public cp_ListarRegistroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this._Contraseña = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this._Tipo = value;
				}
			}
		}
	}
	
	public partial class cp_ListarLoginResult
	{
		
		private string _Nombre;
		
		private string _Contraseña;
		
		private string _Cedula;
		
		public cp_ListarLoginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this._Contraseña = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
	}
	
	public partial class cp_ListarMedicoFiltroResult
	{
		
		private int _idMedico;
		
		private string _Titulo;
		
		private string _Especialidad;
		
		private string _Estado;
		
		private string _Cedula;
		
		public cp_ListarMedicoFiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMedico", DbType="Int NOT NULL")]
		public int idMedico
		{
			get
			{
				return this._idMedico;
			}
			set
			{
				if ((this._idMedico != value))
				{
					this._idMedico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="VarChar(50)")]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this._Titulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Especialidad", DbType="VarChar(50)")]
		public string Especialidad
		{
			get
			{
				return this._Especialidad;
			}
			set
			{
				if ((this._Especialidad != value))
				{
					this._Especialidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
	}
	
	public partial class cp_ListarMedicoResult
	{
		
		private int _idMedico;
		
		private string _Titulo;
		
		private string _Especialidad;
		
		private string _Estado;
		
		private string _Cedula;
		
		public cp_ListarMedicoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMedico", DbType="Int NOT NULL")]
		public int idMedico
		{
			get
			{
				return this._idMedico;
			}
			set
			{
				if ((this._idMedico != value))
				{
					this._idMedico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="VarChar(50)")]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this._Titulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Especialidad", DbType="VarChar(50)")]
		public string Especialidad
		{
			get
			{
				return this._Especialidad;
			}
			set
			{
				if ((this._Especialidad != value))
				{
					this._Especialidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
	}
	
	public partial class cp_ListarRegistroFiltroResult
	{
		
		private string _Cedula;
		
		private string _Nombre;
		
		private string _Contraseña;
		
		private string _Tipo;
		
		public cp_ListarRegistroFiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this._Contraseña = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this._Tipo = value;
				}
			}
		}
	}
	
	public partial class cp_ListarHistorialPacienteFiltroResult
	{
		
		private int _idRegistroPaciente;
		
		private System.Nullable<int> _NumeroConsultas;
		
		private System.Nullable<System.DateTime> _UltimaFechaConsulta;
		
		private int _idPaciente;
		
		private int _idMedico;
		
		public cp_ListarHistorialPacienteFiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRegistroPaciente", DbType="Int NOT NULL")]
		public int idRegistroPaciente
		{
			get
			{
				return this._idRegistroPaciente;
			}
			set
			{
				if ((this._idRegistroPaciente != value))
				{
					this._idRegistroPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroConsultas", DbType="Int")]
		public System.Nullable<int> NumeroConsultas
		{
			get
			{
				return this._NumeroConsultas;
			}
			set
			{
				if ((this._NumeroConsultas != value))
				{
					this._NumeroConsultas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UltimaFechaConsulta", DbType="DateTime")]
		public System.Nullable<System.DateTime> UltimaFechaConsulta
		{
			get
			{
				return this._UltimaFechaConsulta;
			}
			set
			{
				if ((this._UltimaFechaConsulta != value))
				{
					this._UltimaFechaConsulta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPaciente", DbType="Int NOT NULL")]
		public int idPaciente
		{
			get
			{
				return this._idPaciente;
			}
			set
			{
				if ((this._idPaciente != value))
				{
					this._idPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMedico", DbType="Int NOT NULL")]
		public int idMedico
		{
			get
			{
				return this._idMedico;
			}
			set
			{
				if ((this._idMedico != value))
				{
					this._idMedico = value;
				}
			}
		}
	}
	
	public partial class cp_ListarFichaMedicaFiltroResult
	{
		
		private int _idFichaMedica;
		
		private System.Nullable<int> _idPaciente;
		
		private string _Madre;
		
		private string _Padre;
		
		private string _Estudios;
		
		private string _GrupoSanguineo;
		
		private System.Nullable<int> _Edad;
		
		private string _Peso;
		
		private string _Estatura;
		
		public cp_ListarFichaMedicaFiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idFichaMedica", DbType="Int NOT NULL")]
		public int idFichaMedica
		{
			get
			{
				return this._idFichaMedica;
			}
			set
			{
				if ((this._idFichaMedica != value))
				{
					this._idFichaMedica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPaciente", DbType="Int")]
		public System.Nullable<int> idPaciente
		{
			get
			{
				return this._idPaciente;
			}
			set
			{
				if ((this._idPaciente != value))
				{
					this._idPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Madre", DbType="VarChar(50)")]
		public string Madre
		{
			get
			{
				return this._Madre;
			}
			set
			{
				if ((this._Madre != value))
				{
					this._Madre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Padre", DbType="VarChar(50)")]
		public string Padre
		{
			get
			{
				return this._Padre;
			}
			set
			{
				if ((this._Padre != value))
				{
					this._Padre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estudios", DbType="VarChar(50)")]
		public string Estudios
		{
			get
			{
				return this._Estudios;
			}
			set
			{
				if ((this._Estudios != value))
				{
					this._Estudios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupoSanguineo", DbType="VarChar(20)")]
		public string GrupoSanguineo
		{
			get
			{
				return this._GrupoSanguineo;
			}
			set
			{
				if ((this._GrupoSanguineo != value))
				{
					this._GrupoSanguineo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edad", DbType="Int")]
		public System.Nullable<int> Edad
		{
			get
			{
				return this._Edad;
			}
			set
			{
				if ((this._Edad != value))
				{
					this._Edad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Peso", DbType="VarChar(20)")]
		public string Peso
		{
			get
			{
				return this._Peso;
			}
			set
			{
				if ((this._Peso != value))
				{
					this._Peso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatura", DbType="VarChar(20)")]
		public string Estatura
		{
			get
			{
				return this._Estatura;
			}
			set
			{
				if ((this._Estatura != value))
				{
					this._Estatura = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
